---
version: "3.5"
services:
  jupyter:
    container_name: jupyter
    build:
      context: ./jupyter
      dockerfile: Dockerfile
    privileged: true
    restart: unless-stopped
    ports:
      - 0.0.0.0:9001:9001
      - 0.0.0.0:6006:6006 # for TensorBoard
    volumes:
      - ./notebooks:/notebooks
      - ./jupyter/overrides.json:/usr/local/share/jupyter/lab/settings/overrides.json
    environment:
      - JUPYTER_TOKEN=12345
    devices:
      - /dev/nvidia-uvm
      - /dev/nvidia-uvm-tools
      - /dev/nvidia-modeset
      - /dev/nvidiactl
      - /dev/nvidia0
    ulimits:
      memlock: -1
      stack: 67108864
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]



