---
version: "3.5"
services:
  jupyter:
    container_name: jupyter
    build:
      context: ./jupyter
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 0.0.0.0:9001:9001
    volumes:
      - ./notebooks:/notebooks
      - ./jupyter/overrides.json:/opt/conda/share/jupyter/lab/settings/overrides.json
    environment:
      - JUPYTER_TOKEN=12345
    devices:
      - /dev/nvidia-uvm
      - /dev/nvidia-uvm-tools
      - /dev/nvidia-modeset
      - /dev/nvidiactl
      - /dev/nvidia0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu


